chromedriver_path: /usr/local/bin/chromedriver
sites:
# warning: tag is xpath expression, think to chage it you use BeautifulSoup selector
  cdiscount:
    name: Cdiscount
    url: https://www.cdiscount.com
    target_pattern: (\/f-\d+.*\.html)|(\/mpv.*-\d+.*\.html)
    absolute_url: True

    tags:
      title: //h1[@itemprop="name"] 
      ean: //*[contains(text(),'pr_ean')]
      price: //span[@class="fpPrice price priceColor jsMainPrice jsProductPrice hideFromPro" and @itemprop="price"]//text()
      seller: //a[@class="fpSellerName"] # if no seller, then it's Cdiscount
      captcha: //div[contains(@class, "white-square")][contains(@p, "")]
      seller_listing: //p[@class="fpOtherOffer"]//@href # //p[@class="fpOtherOffer"]/a/@href
      mp_sellers_prices: //p[@class="price priceColor"]//text()
      website_seller_price:
      image_product : //ul[@class="jsFpZoomPic smallPic"]//@src
      description : //div[@id="fpBulletPointReadMore"]
      offer_count : //p[@class="fpOtherOffer"]
      seller_price : //div[@class="fpBlk fpTab"]//text()
      seller_name: //div[@class="fpBlk fpTab"]//text()
      shipping_rate_price: //div[@class="fpBlk fpTab"]//text()
      expedition_country: //div[@class="fpBlk fpTab"]//text()
      send_by_cdiscount : //div[@class="fpBlk fpTab"]//text()
      sales_realized : //div[@class="fpBlk fpTab"]//text()
      state: //div[@class="fpBlk fpTab"]//text()
      seller_rating :  //div[@class="fpBlk fpTab"]//text()


    patterns:
      ean: (\["pr_ean"\]=).(\d+)
      seller_price : (\d+\n€\d+)(.*)
      seller_name: (.*\n.)(\n.*)(\d+\n€\d+)
      shipping_rate_price : (.*\n.*)(?=Disponibilité)(.*)
      expedition_country: 
      send_by_cdiscount : 
      sales_realized :
      state: 
      seller_rating : 

    
    groups:
      ean: 2
