chromedriver_path: /usr/local/bin/chromedriver
sites:
# warning: tag is xpath expression, think to chage it you use BeautifulSoup selector
  cdiscount:
    name: Cdiscount
    url: https://www.cdiscount.com
    target_pattern: (\/f-\d+.*\.html)|(\/mpv.*-\d+.*\.html)
    absolute_url: True
    link_product_home_page: //a[@class="o-card__link flow--xs"]

    tags:
      title: //h1[@itemprop="name"] 
      ean: //*[contains(text(),'pr_ean')]
      seller_price: //span[@class="fpPrice price priceColor jsMainPrice jsProductPrice hideFromPro" and @itemprop="price"]//text()
      seller: //a[@class="fpSellerName"] # if no seller, then it's Cdiscount
      captcha: //div[contains(@class, "white-square")][contains(@p, "")]
      seller_listing: //p[@class="fpOtherOffer"]//@href # //p[@class="fpOtherOffer"]/a/@href
      product_image: //ul[@class="jsFpZoomPic smallPic"]//@src
      description: //div[@id="fpBulletPointReadMore"]
      offer_count: //p[@class="fpOtherOffer"]


    patterns:
      ean: (\["pr_ean"\]=).(\d+)
      seller_price: (\d+\n€\d+)(.*)
      seller_name: (.*\n.)(\n.*)(\d+\n€\d+)
      shipping_rate_price: (.*\n.*)(?=Disponibilité)(.*)
      expedition_country: (Expédié par :)\n(.*)
      #send_by_cdiscount: 
      sales_realized: Cdiscount|Ventes réalisées :(\n.*\d+)(.*)
      state: (.*\n)(.*\n.*)(?=Disponibilité)
      seller_rating: Cdiscount|(Évaluation(.*)\n(.*))

    groups:
      ean: 2
      seller_price: 0
      seller_name: 0
      shipping_rate_price: 0
      expedition_country: 1
      sales_realized: 0
      seller_rating: 0
  
    tags_get_from_seller_listing:
      seller_price: //div[@class="fpBlk fpTab"]//text()
      seller_name: //div[@class="fpBlk fpTab"]//text()
      shipping_rate_price: //div[@class="fpBlk fpTab"]//text()
      expedition_country: //div[@class="fpBlk fpTab"]//text()
      sales_realized: //div[@class="fpBlk fpTab"]//text()
      seller_rating:  //div[@class="fpBlk fpTab"]//text()
      state: //div[@class="fpBlk fpTab"]//text()
      #commom_tag: //div[@class="fpBlk fpTab"]//text()
